apiVersion: 1
datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
  - name: Core API
    uid: core-api
    type: yesoreyeram-infinity-datasource
    jsonData:
      allowedHosts: [http://core:8000]
